services:
  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
     - ./api:/api:cached
    env_file:
      - ./.env
    networks:
     - db_network
     - api_network
    restart: on-failure

  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    networks:
     - db_network
    volumes:
      #- ${DB_PATH}:
      - /var/lib/postgresql/data

##
# DEBUG CONTAINERS --profile debug
##
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    networks:
      - db_network
    volumes:
      - ${PGADMIN_PATH}:/var/lib/pgadmin:cached
    ports:
      - "5050:80"
    profiles:
      - debug

networks:
  db_network:
  api_network:
